### ISSUE TITLE
`train_num_task` and `test_num_task`

### ISSUE THREAD

**Issue by iamgroot42** [MinChen00/Face-Auditor#2]
Hey,

What do the values of `train_num_task` and `test_num_task` correspond to? Looking at the codebase I thought it might be the number of iterations per epoch, but am not sure how these values are picked (default of 100 and 80 respectively) and how they would map to the experimental setup in the paper. 

Thanks!

**Comment by MinChen00** [comment]
These two parameters are discarded in the latest version, and we use the `probe_times` and `test_times` instead, which should be easier to comprehend.

**Comment by iamgroot42** [comment]
Great- thanks, @MinChen00 ! Is the version with `probe_times` (and the corresponding values to be used for different datasets) available elsewhere?
