### ISSUE TITLE
Questions about attack setup

### ISSUE THREAD

**Issue by iamgroot42** [MinChen00/Face-Auditor#4]
Hey,

I had a couple of questions regarding the code structure (specifically the attack setup)

1. The following:
https://github.com/MinChen00/Face-Auditor/blob/f9942d2958fee769077d758534fb4d6969c5944f/exp/exp_class_mem_infer.py#L51 

    seems to be computing train-metrics for the shadow model, but uses `self.attack_train_data` and `self.attack_test_label`. If I understand correctly, the latter should be `self.attack_train_label`? Or is it the case that they are equivalent? 

    On a side note, `.test_model_acc` (in the line above) and on L60, 61 seem to be called twice- is there a reason to do so?

2. From my understanding after looking at the following:
https://github.com/MinChen00/Face-Auditor/blob/f9942d2958fee769077d758534fb4d6969c5944f/exp/exp_memguard_meta.py#L152

    the meta-classifier is trained to predict `0` if the user was part of training?

**Comment by MinChen00** [comment]
Hi, for the first question, we calculate the train/test accuracy and AUC respectively.

For the second question, you're correct. We use zeros for member users and ones for non-member users.
