### ISSUE TITLE
Using .mean() instead of .sum() in RelationNets 

### ISSUE THREAD

**Issue by iamgroot42** [MinChen00/Face-Auditor#5]
https://github.com/MinChen00/Face-Auditor/blob/f9942d2958fee769077d758534fb4d6969c5944f/lib_model/relation_net/relation_net.py#L250

Is there a reason to be using `.sum()` here instead of a `.mean()` as it is used in ProtoNets? From my understanding, `.sum()` would make the learned relation model potentially give different weights to the support set and may make it harder to extend at test time for different values of _l_ in l-shot

**Comment by MinChen00** [comment]
The workflow of relationnet and protonet is different as they aim to solve different scenarios, and I follow the original implementation of the relationnnet, see [https://github.com/floodsung/LearningToCompare_FSL](https://github.com/floodsung/LearningToCompare_FSL).

**Comment by iamgroot42** [comment]
I see- I think the original implementation should also be using `.mean()` For instance, if one trains a RelationNet with 5-shot at training time but wants to extend/test it later when it has maybe more images/per person, it would make more sense to use the `.mean()` than to use `.sum()` and then scale it (divide /2 in this example). Thanks for the clarification :)
