### ISSUE TITLE
Gradient-norm clipping

### ISSUE THREAD

**Issue by iamgroot42** [MinChen00/Face-Auditor#6]
Is there a reason to clip gradient normals for normal training, specifically for RelationNet?

https://github.com/MinChen00/Face-Auditor/blob/f9942d2958fee769077d758534fb4d6969c5944f/lib_model/relation_net/relation_net.py#L101

**Comment by MinChen00** [comment]
I am unsure about this clip, as I follow the original implementation of the relationnet, see [https://github.com/floodsung/LearningToCompare_FSL](https://github.com/floodsung/LearningToCompare_FSL).
