### ISSUE TITLE
Audit member/non-member split logic

### ISSUE THREAD

**Issue by iamgroot42** [MinChen00/Face-Auditor#8]
I had a question about the member and non-member split in this line: 

https://github.com/MinChen00/Face-Auditor/blob/f9942d2958fee769077d758534fb4d6969c5944f/lib_dataset/preprocess.py#L61C3-L61C3

From what I understand:
- The comment actually means UMDFaces
- The '20' comes from the fact that 10% of all users (so 200 * 0.1) are used each as members and non-members for training and testing the auditing model.

**Comment by MinChen00** [comment]
The `20` means each user has a maximum of 20 images, which is the case for the preprocessed CelebA dataset. In the code, `train_mem_indices` represents the member users' training images, while `train_nonmem_indices` represents the member users' non-training images.
