### ISSUE TITLE
Meta-classifier probing when queries not sorted

### ISSUE THREAD

**Issue by iamgroot42** [MinChen00/Face-Auditor#9]
When `is_sort_query` is False for probing shadow models, the code seems to be accidentally using the target's data for collecting data for the shadow model, instead of the shadow's data. This might lead to over-estimation of the meta-classifier's performance when tested with `is_sort_query=False`

https://github.com/MinChen00/Face-Auditor/blob/f9942d2958fee769077d758534fb4d6969c5944f/exp/exp_class_mem_infer_meta.py#L151C1-L151C1

**Comment by MinChen00** [comment]
Thanks for pointing this out and it should be the typo. We set the default value of `is_sort_query` to `True` so I omitted this typo.

**Comment by iamgroot42** [comment]
My bad- relooking at the code (I did not see the `not` earlier), I meant to say that it uses target data when `is_sort_query=True`, which is the default indeed.
